### ISSUE TITLE
remake for spatial data

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#108]
one big file for points and catchments, probably a shapefile

**Comment by jread-usgs** [comment]
Raises hand. "Can I do it?"

**Comment by jread-usgs** [comment]
Note we have a lot of datasets that depend on the site make.

**Comment by aappling-usgs** [comment]
Have fun! Yes, the site list is fundamental - do you have concerns or are you just observing?

**Comment by jread-usgs** [comment]
just noting that we might want to consider it a priority

**Comment by aappling-usgs** [comment]
consider it prioritized

**Comment by jread-usgs** [comment]
great. Can you #mention this issue when #101 is completed and merged?

**Comment by aappling-usgs** [comment]
will do!

**Comment by jread-usgs** [comment]
having dealt with a bit of pain on the GAGESII dataset (https://github.com/USGS-R/geoknife/issues/289), I was able to compare sites in GAGESII vs sites in BASINS. There is a lot of overlap (as expected), but there are some sites in GAGESII that are not in BASINS and vice versa. So, by including both, we get a bit more coverage:

```r
sum(pow.ids %in% gages.id | pow.ids %in% basins.id)
288
```
out of 392. is 261 or 262 matches for each of those datasets individually.

**Comment by jread-usgs** [comment]
@aappling-usgs I got stuck on merging the two basins shapefiles (WIP on my branch), and now I am going to be occupied for a couple of weeks. Thoughts on pulling in David to help finish that part of the task? Then we can start the work to fill in the last catchments through other means.

**Comment by aappling-usgs** [comment]
good with me.

**Comment by jread-usgs** [comment]
need #181 to complete this one
