### ISSUE TITLE
add file staging for calculated DO.sat, depth, and light

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#11]
these are the variables currently needed (assuming doobs="DO.obs" and wtr="temp.water" are already available on SB) to run metab_mle

**Comment by jread-usgs** [comment]
I sense we may need another sprint soon?

**Comment by aappling-usgs** [comment]
could we sprint on tests for mda.streams?

**Comment by jread-usgs** [comment]
:hamburger:

**Comment by aappling-usgs** [comment]
finished with #24
