### ISSUE TITLE
location/tracking of config info

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#111]
Where should the `on_exists` preference live for sites, metadata, and ts files?

1. sites - we currently just use the default `on_exists` value for `post_site` (it's 'stop'), and also never even try to post sites that already exist
2. metadata - we currently force `on_exists` to be 'replace'
3. ts - the user's choice for `on_exists` currently lives in ts_config.yaml and is loaded by `sb_post_ts()` despite the fact that we've explicitly removed other dependencies of this function call on the config file

Earlier today we agreed that we wanted to copy over some config fields into the status tables for sites and ts files - specifically, ts status tables get columns for `time.st` and `time.en`, and site status tables get columns for `min.count`, `skip.types`, and `has.param`. We decided to do this to (1) have a complete record of decisions for each site in the tables alone, and (2) avoid having later stages like sb_post depend on the ts_config or sites_config files.

In light of the above question/observations, I think we should add `on_exists` to sites_config.yaml and create a meta_config.yaml with an `on_exists` field. From there I see two ways forward:

1. add columns for `on_exists` to the site and ts status tables, and create a metadata status table (1 row so far) with an `on_exists` column. i don't love this option because it adds even more redundancy and requires creation of a new, otherwise useless, table.
2. from sb_post_ts, sb_post_site, and sb_post_meta, check the respective config files to decide how to handle pre-existing items. If we do this, I'd advocate for taking `time.st`, `time.en`, `min.count`, `skip.types`, and `has.param` back out of the ts and site status tables, because to have config info split between the config file and the status tables is messy.

@jread-usgs , can I sell you on option 2? To make my case further, let me point out that while multiple dependencies on the config files got you in trouble in past projects (because remake had to remake a lot of steps if the config file changed), that risk is mitigated here because we've make each config file quite small and relevant to only a small number of processing steps.

**Comment by jread-usgs** [comment]
yes, I agree. I think the second option is better and I 👍 it

**Comment by aappling-usgs** [comment]
excellent. i will implement it.
