### ISSUE TITLE
small external spatial data example

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#117]

**Comment by jread-usgs** [comment]
are we still including this in the ms?

**Comment by aappling-usgs** [comment]
i hope to, yes

**Comment by aappling-usgs** [comment]
you interested in taking it on?

**Comment by jread-usgs** [comment]
What is the scope? Something w/ GDP and NLCD?

**Comment by aappling-usgs** [comment]
That would be fine. It's pretty free-form - probably means adding a paragraph and some code to the Usage section, to be one of several examples of how to use the code. Goal would be to show people what's possible as a result of us including catchment shapefiles (or points) in the release, and to give them a foothold for approaching that task. Anything that achieves those goals is a winner; this example doesn't need to provide any scientific insight, and we are unlikely to have space for an additional figure. 

One possibility would be to identify the dominant land use class using catchments, and then to use that information as the basis for the 3rd planned panel of `figure: site info` (#186), which is "histograms of land use classes: urban vs ag vs everything else". That figure would appear much earlier than this example in the paper, but then in this example we could say ("and see, this is how we produced Fig 1").

**Comment by jread-usgs** [comment]
So that would process the NLCD against the catchment shapefile?

**Comment by aappling-usgs** [comment]
Yes. Is that a reasonable and sufficiently interesting geoknife task?

**Comment by jread-usgs** [comment]
well...it is a bit complicated because the NLCD services are broken for a GDP analysis, so you actually need to download it and process w/ raster pkg and/or `sf`. A lot easier to provide a timeseries example, but that would be less useful to people.

**Comment by aappling-usgs** [comment]
ah, ok. can you think of any lower-hanging spatial fruit we can pluck? any dataset for which services aren't broken? mean annual air temperature, population density, median land slope? what about mean precip in 2017 for all catchments and mean projected precip in 2030 for all catchments, then give results of t-test or linear model or something showing the range of precip changes predicted for the population of modeled rivers?...i'm grasping at straws here. ideas welcome.

**Comment by aappling-usgs** [comment]
i'm thinking we don't bother with this after all - the Usage sections of other NSD papers are really short and contain no code.
