### ISSUE TITLE
automate NHD+ ID-getting

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#119]
We would like to use the nldi/sqp service to match NWIS IDs to NHD+ IDs. As we do this, we'd like to note any discrepancies between this method and previous methods.

```
query <- httr::GET('http://notsharingthispart/nldi/wqp/USGS-385520094420000/navigate/UM/wqp?distance=1') %>% httr::content(as = 'text') %>% jsonlite::fromJSON()
```

We already have two sources of info on the match between NWIS station IDs and NHD+ COM IDs. The first (from Ted) is labeled `nhdplus_id` below. The second (from Jud) is labeled `jud_nhdplus_id`. Modifying code in the function `stage_meta_dvqcoefs` gives us this comparison (on 7/14/2016):

```
meta_basic <- unitted::v(get_meta('basic'))
jud_coefs <- read.table(system.file("extdata/RatingCurves_JudHarvey.tsv", package="mda.streams"), header=T, sep="\t", colClasses="character")
col='nhdplus_id'; jud_coefs[jud_coefs[,col]=='-9999',col] <- NA
meta_basic$site_num <- as.numeric(meta_basic$site_num)
meta_basic$nhdplus_id <- as.numeric(meta_basic$nhdplus_id)
meta_basic$jud_nhdplus_id <- jud_coefs[match(meta_basic$site_num, jud_coefs$site_num), 'nhdplus_id']
out <- meta_basic[, c('site_name', 'nhdplus_id', 'jud_nhdplus_id')] %>% mutate(matched=(is.na(nhdplus_id) & is.na(jud_nhdplus_id) | (nhdplus_id==jud_nhdplus_id))) %>% filter(grepl('nwis', site_name))
saveRDS(out, 'temp/nhdplus_id_comparison.Rds')
```

The resulting comparison file is here: [nhdplus_id_comparison.zip](https://github.com/USGS-CIDA/stream_metab_usa/files/363958/nhdplus_id_comparison.zip)

**Comment by aappling-usgs** [comment]
Just talked with Dave S and Jim about this. The bad news: not all NWIS IDs are there - only those also in GAGES II. The good news: it's easy for Dave & Jim to add a set of NWIS IDs. All they need is a shapefile (cue your work this morning, @jread-usgs !) on sciencebase (anywhere, as long as it's public, and eventually they want to add tags to that item), plus an email with some information about how to link to the shapefile.

The shapefile should include (1) the site points, (2) the NWIS IDs, (3) the short names from NWIS, and optionally (4) a URI linking out to the NWIS page for that site.

The email should give (A) the URI of the shapefile (e.g., to the sciencebase item) and (B) the names of the columns/features where items 2-4 above are stored.

Given that information, Jim & Dave can add our shapefile to the list that NLDI indexes, and then all of our sites will be available through the NLDI API with links to the NHD COM IDs, etc.

Other info that might be of interest for linking to other datasets could be the reach codes (most reaches are made of several COM ID flow lines) and possibly the Measures, which are the start and end points of each COM ID flow line expressed as percent distances along the full reach.

**Comment by jread-usgs** [comment]
Awesome!

**Comment by jread-usgs** [comment]
Before we ship them that shapefile, should we see how many of our sites are already indexed? I didn't run into any that weren't when I was playing around with it, but wouldn't be surprised if some were missing.

**Comment by aappling-usgs** [comment]
Sure, sounds good. I was thinking that if we did ship them the shapefile, we'd actually do it by just adding a couple of columns to your current points shapefile, posting it to the same place we'd have posted it to anyway for the data paper, and sending them a link to the shapefile where it already lives. So I'm hoping it wouldn't be a lot of work or one-off effort for us either way, but checking first would help keep NLDI lean. Jordan, you interested in doing the checking?

**Comment by aappling-usgs** [comment]
A little more example code, pulled from Slack because I keep losing it there:
```
library(dplyr)
query <- httr::GET('http://notsharingthispart/nldi/wqp/USGS-385520094420000/navigate/UM/wqp?distance=1') %>% 
  httr::content(as = 'text') %>% jsonlite::fromJSON()

coords <- lapply(query$features$geometry$coordinates, function(crd) as.list(crd) %>%
                   setNames(c('lon','lat')) %>% as.data.frame()) %>% bind_rows() %>% 
  bind_cols(select(query$features$properties, identifier, name))

library(leaflet)
leaflet() %>% addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=coords$lon, lat=coords$lat, popup=coords$name)
```

**Comment by aappling-usgs** [comment]
And still more, specific to getting COMIDs for our sites:
```r
sitenums <- list_sites() %>% 
  parse_site_name(out=c('sitenum','database')) %>%
  filter(database=='nwis') %>%
  .$sitenum
comids <- sapply(setNames(nm=sitenums[1:10]), function(sitenum) {
  query <- httr::GET(paste0('http://notsharingthispart/nldi/wqp/USGS-',sitenum,'/navigate/UM/wqp?distance=0.5')) %>% 
    httr::content(as = 'text', encoding = "UTF-8") %>% jsonlite::fromJSON()
  
  oursite <- grep(paste0('USGS-',sitenum), ((query$features)$properties)$identifier)
  
  query$features[3,'properties']$comid
})
```

**Comment by aappling-usgs** [comment]
tried out the NLDI approach at https://github.com/USGS-R/mda.streams/blob/develop/R/stage_meta_basic.R#L198-L205. also got hand-curated estimates from ted and updates from jud. we're content.
