### ISSUE TITLE
get units out of gldas

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#124]
right now even with result(with.units=TRUE) we're getting NA in the units from gldas.

**Comment by jread-usgs** [comment]
related to https://github.com/USGS-CIDA/stream_metab_usa/issues/86

**Comment by jread-usgs** [comment]
Yeah, units are not being written to the ncml anymore (not sure why), so this bug makes sense:

https://github.com/USGS-CIDA/stream_metab_usa/blob/master/1_ldas_host/out/gldas.ncml vs https://github.com/USGS-CIDA/stream_metab_usa/blob/c4d7a61f514a5f0fa3b0ea37d3142bd3b58af3be/p1_import/out/gldas.ncml is what it should look like

**Comment by aappling-usgs** [comment]
not worth it
