### ISSUE TITLE
Snapshot: Spatial data

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#134]
Spatial data
File: XML metadata
File: one large shapefile that includes points and polygons (polygon per catchment starting at monitoring point) for all site

**Comment by jread-usgs** [comment]
- [ ] automated metadata extraction (e.g., `wbbox` and `states`)

**Comment by jread-usgs** [comment]
this work is going on in [meddle](https://github.com/USGS-R/meddle)

**Comment by aappling-usgs** [comment]
this is mostly done or duplicated in #108 and #181, so closing this issue
