### ISSUE TITLE
Figure out best way for staging file chunks

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#14]
for `stage_nldas_ts`, I am concerned that we probably won't be able to pull the full record in one geojob - which makes me think it needs to be split into multiple jobs and then stitched back together. We don't currently support this elegantly, but it isn't just this edge-case. Think of wanting to grab the next 6 months of NWIS after we have been working on this project - we may just want to tack on (append) the new dates to the existing files?

**Comment by aappling-usgs** [comment]
I like the idea of providing for appends. Here's how we might do it:
- I put in an argument to `post_ts` called `on_exists` that currently accepts `c('stop','skip','replace')` but should in the future also accept `'append'`: https://github.com/USGS-R/mda.streams/pull/92/files#diff-e39b8ff689ff23a9ada21e585f61e4eeR19 and https://github.com/USGS-R/mda.streams/pull/92/files#diff-e39b8ff689ff23a9ada21e585f61e4eeR38. 
- Once that's implemented, then we need to implement a way to figure out what date range is already available in a time series (`mda.streams::summarize_ts()`?) 
- Then in `stream_metab_usa/p1_import` we can find out what dates are needed, download just that part, and call `post_ts` with `on_exists==append`. 
- This should allow us to do even the initial data download in chunks - each time, we simply download no more than, say, a year worth of data at a time, and we keep calling the import script until `stream_metab_usa/p1_import` can reach the conclusion (in the form of a signalling file) that the data are up to date. 

Sound like a plan?

**Comment by aappling-usgs** [comment]
`post_ts` has a `merge` argument now.
