### ISSUE TITLE
get NLDAS data into SB via makefile

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#16]

**Comment by jread-usgs** [comment]
@aappling-usgs I see what you did in #15 , but I think it is more efficient for the geoknife calls to chunk time instead of sites, so I will modify the pattern you have in `02_add_nldas_data.R` accordingly (unless you would prefer otherwise).

**Comment by aappling-usgs** [comment]
efficiency is great. chunk away!

**Comment by jread-usgs** [comment]
are you satisfied with the current state of this part of the make?

**Comment by aappling-usgs** [comment]
yes, i am. you used this script as-is to bring in the nldas data, didn't
you?

On Thu, Sep 10, 2015 at 2:50 PM, Jordan S Read <notifications@github.com>
wrote:

> are you satisfied with the current state of this part of the make?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CIDA/stream_metab_usa/issues/16#issuecomment-139361317>
> .
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Center for Integrated Data Analytics and University of Wisconsin -
Madison
Phone: (608) 821-3927
