### ISSUE TITLE
data pull with full 2016 data

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#166]
happening at #164 , but want to capture progress and challenges here. 

- [ ]  we have run into sites with duplicate dates from NWIS. Who should this be reported to?
- [ ]  running into output with -99999 error codes as values (e.g., `nwis_03277200` for `wtr`)
- [x] updated authentication for nasa data services
- [x] 'calc_velocity' is deprecated in [`streamMetabolizer`](https://github.com/USGS-R/streamMetabolizer)
- [x] waiting on new velocity coefficients for derived data
- [ ] `update_item` in sbtools fails poorly when an item has [read access but not write access](https://github.com/USGS-R/sbtools/issues/226)
- [x] GLDAS data lags more than NLDAS, so only data up to 12/31/2016 were available (vs NLDAS is a 3(?) day lag from present day). 
- [x] stale data tables give us an error: `checking timeseries status on ScienceBase
 Error in dirname(file_name) : a character vector argument expected`. Needed to delete those targets completely to avoid this error. We also get this error when all sites are `no.data==TRUE`, which is the case for the target below `dosat_calcGGbconst`. 
- [x] `dosat_calcGGbconst` target ends up all empty for all sites.

**Comment by jread-usgs** [comment]
For the dosat_calcGGbconst, 
This seems to be because 
```r
'dosat_calcGGbconst' = {
            wtr_best <- get_staging_ts(choose_ts('wtr'))
            baro_const <- if('baro_src' %in% names(inputs)) {
              ignore <- get_staging_ts('baro_src') # just so the choice gets logged
              inputs$baro_src 
            } else {
              get_staging_ts('baro_calcElev')
            }
Error in get_staging_ts("baro_calcElev") : 
  with var_src=c(baro_calcElev), site=nwis_03025500, version=rds: no complete rows returned
```
but within `get_staging_ts` 
```r
  get_staging_ts <- function(var_src, ...) {
    choices <<- c(choices, setNames(parse_var_src(var_src, out='src'), paste0('var.', parse_var_src(var_src, out='var'))))
    ts <- get_ts(var_src, site, version=with_ts_version, on_local_exists="replace", ..., quietly=TRUE) # only finds non-archived, ignores upload dates
    ts <- ts[complete.cases(ts),]
    if(nrow(ts) == 0) 
      stop('with var_src=c(',paste0(var_src, collapse=', '),'), site=',site,', version=',with_ts_version,': no complete rows returned')
    ts
  }
```
the `get_ts` works and returns 
```
DateTime     baro
U                Pa
1       NA 97884.91
```
but the next line w/ `complete.cases(ts)` removes it, so you end up with 
```
DateTime baro
U            Pa
<0 rows> (or 0-length row.names)
```

**Comment by jread-usgs** [comment]
talking w/ @aappling-usgs, and will check for the form of the constant and skip the `complete.cases()` function if nrow == 1 & is.na(DateTime), and !is.na(value)

**Comment by aappling-usgs** [comment]
status this morning (for jordan's computer, where `local` > 0):

|var_src                | total| untouched| no_data| local| posted_untagged| posted_tagged| uncounted| barheight|
|:----------------------|-----:|---------:|-------:|-----:|---------------:|-------------:|---------:|---------:|
|doobs_nwis             |   734|         0|      62|     0|               0|           672|         0|       734|
|wtr_nwis               |   734|         0|      57|     0|               0|           677|         0|       734|
|disch_nwis             |   734|         0|     309|     0|               0|           425|         0|       734|
|baro_nldas             |   734|         0|      13|     0|               0|           721|         0|       734|
|sw_nldas               |   734|         0|      13|     0|               0|           721|         0|       734|
|baro_gldas             |   734|         0|      30|     0|               0|           704|         0|       734|
|sw_gldas               |   734|         0|      30|     0|               0|           704|         0|       734|
|dosat_calcGGbts        |   734|         0|      60|     0|               0|           674|         0|       734|
|baro_calcElev          |   734|         0|     168|     0|               0|           566|         0|       734|
|dosat_calcGGbconst     |   734|         0|     210|     0|               0|           524|         0|       734|
|dopsat_calcObsSat      |   734|         0|      66|     0|               0|           668|         0|       734|
|depth_calcDischRaymond |   734|         0|     309|   425|               0|             0|         0|       734|
|veloc_calcDischRaymond |   734|       424|     309|     1|               0|             0|         0|       734|
|depth_calcDischHarvey  |    NA|        NA|      NA|    NA|              NA|            NA|        NA|        NA|
|veloc_calcDischHarvey  |    NA|        NA|      NA|    NA|              NA|            NA|        NA|        NA|
|sitetime_calcLon       |   734|         0|      62|     0|               0|           672|         0|       734|
|suntime_calcLon        |   734|         0|      62|     0|               0|           672|         0|       734|
|par_calcLat            |   734|         0|      62|     0|               0|           672|         0|       734|
|par_calcSw             |   734|         0|      10|     0|               0|           724|         0|       734|
|sitedate_calcLon       |   734|         0|      62|     0|               0|           672|         0|       734|
|doamp_calcDAmp         |    NA|        NA|      NA|    NA|              NA|            NA|        NA|        NA|
|dischdaily_calcDMean   |    NA|        NA|      NA|    NA|              NA|            NA|        NA|        NA|
|velocdaily_calcDMean   |    NA|        NA|      NA|    NA|              NA|            NA|        NA|        NA|
|NA                     |   734|       650|      12|    72|               0|             0|         0|       734|

![all_ts_files](https://cloud.githubusercontent.com/assets/12039957/22474850/7202e69e-e79a-11e6-9c6d-1285b1466e26.png)

**Comment by aappling-usgs** [comment]
Need to re-calculate par_calcLatSw because I found a bug on the streamMetabolizer side. To do so, I'm running these lines manually:
```r
var_src='par_calcLatSw'
to.archive <- summarize_ts_files(var_src) %>%
    filter(!is_archive, upload_date < as.POSIXct("2017-01-30"))
mda.streams:::archive_ts(ts_id=to.archive$ts_item, filename=to.archive$file_name)
```

**Comment by aappling-usgs** [comment]
Many of the ts status files I was looking at were out of date: see how relative to the total number of sites, they're now showing 17 uncounted:
![image](https://cloud.githubusercontent.com/assets/12039957/22515252/1b138166-e85f-11e6-9364-fde6b6f4d713.png)
I think blowing away the old status files is the solution here, so I'm doing that now. It's currently leading to new data pulls for 79 sites for doobs_nwis (some of which are unavailable, but many of which are now being downloaded).

**Comment by aappling-usgs** [comment]
Jordan has reminded me that he was using the old site list on purpose, because we won't have new coefficients or NPDES data for any of the new sites.

**Comment by aappling-usgs** [comment]
|var_src                | total| untouched| no_data| local| posted_untagged| posted_tagged| uncounted| barheight|
|:----------------------|-----:|---------:|-------:|-----:|---------------:|-------------:|---------:|---------:|
|doobs_nwis             |   751|         0|      52|     0|               0|           699|         0|       751|
|wtr_nwis               |   751|         0|      48|     0|               0|           703|         0|       751|
|disch_nwis             |   751|         0|     314|     0|               0|           437|         0|       751|
|baro_nldas             |   751|         0|      32|     0|               0|           719|         0|       751|
|sw_nldas               |   751|         0|      32|     0|               0|           719|         0|       751|
|baro_gldas             |   751|         0|      49|     0|               0|           702|         0|       751|
|sw_gldas               |   751|         0|      49|     0|               0|           702|         0|       751|
|dosat_calcGGbts        |   751|         0|      77|     0|               0|           674|         0|       751|
|baro_calcElev          |   751|         0|     172|     0|               0|           579|         0|       751|
|dosat_calcGGbconst     |   751|         0|     202|     0|               0|           549|         0|       751|
|dopsat_calcObsSat      |   751|         0|      63|     0|               0|           688|         0|       751|
|depth_calcDischRaymond |   751|         0|     314|     0|               0|           437|         0|       751|
|veloc_calcDischRaymond |   751|         0|     314|     0|               0|           437|         0|       751|
|depth_calcDischHarvey  |   751|         0|     364|     0|               0|           387|         0|       751|
|veloc_calcDischHarvey  |   751|         0|     364|     0|               0|           387|         0|       751|
|sitetime_calcLon       |   751|         0|      52|     0|               0|           699|         0|       751|
|suntime_calcLon        |   751|         0|      52|     0|               0|           699|         0|       751|
|par_calcLat            |   751|         0|      52|     0|               0|           699|         0|       751|
|par_calcSw             |   751|         0|      29|     0|               0|           722|         0|       751|
|par_calcLatSw          |   751|         0|      80|     0|               0|           671|         0|       751|
|sitedate_calcLon       |   751|         0|      52|     0|               0|           699|         0|       751|
|doamp_calcDAmp         |   751|         0|      65|     0|               0|           686|         0|       751|
|dischdaily_calcDMean   |   751|         0|     335|     0|               0|           416|         0|       751|
|velocdaily_calcDMean   |   751|         0|     335|     0|               0|           416|         0|       751|

![image](https://cloud.githubusercontent.com/assets/12039957/22565178/7cf5d470-e944-11e6-9850-e1f7d0ad2350.png)

Currently retrying for those last few sites for baro and sw; otherwise looking really good!

**Comment by aappling-usgs** [comment]
progress on the data re-re-pull of NLDAS and GLDAS data now that GDP is back up:
```
[ BUILD ] baro_nldas                                              |  baro_nldas <- stage_ts("../1_timeseries/out/files_ts_baro_nldas.tsv")
#### STAGING TSES: ATTEMPT 1 ####
staging data for 32 new sites; 719 are already local/posted/unavailable; 751 sites total
omitting these sites for lack of coordinates: 
applying 2 day offset to request due to data hosting bug
starting remote processing and data download
finished downloading data; now writing to file[s]
site nwis_15236900 has all NA values. Skipping file write***new***
site nwis_15298040 has all NA values. Skipping file write
site nwis_50048565 has all NA values. Skipping file write
site nwis_50048580 has all NA values. Skipping file write
site nwis_50231500 has all NA values. Skipping file write
site nwis_50231505 has all NA values. Skipping file write
[ BUILD ] sw_nldas                                                |  sw_nldas <- stage_ts("../1_timeseries/out/files_ts_sw_nldas.tsv")
#### STAGING TSES: ATTEMPT 1 ####
staging data for 32 new sites; 719 are already local/posted/unavailable; 751 sites total
omitting these sites for lack of coordinates: 
applying 2 day offset to request due to data hosting bug
starting remote processing and data download
finished downloading data; now writing to file[s]
site nwis_15236900 has all NA values. Skipping file write***new***
site nwis_15298040 has all NA values. Skipping file write
site nwis_50048565 has all NA values. Skipping file write
site nwis_50048580 has all NA values. Skipping file write
site nwis_50231500 has all NA values. Skipping file write
site nwis_50231505 has all NA values. Skipping file write
[ BUILD ] baro_gldas                                              |  baro_gldas <- stage_ts("../1_timeseries/out/files_ts_baro_gldas.tsv")
#### STAGING TSES: ATTEMPT 1 ####
staging data for 49 new sites; 702 are already local/posted/unavailable; 751 sites total
omitting these sites for lack of coordinates: 
applying 2 day offset to request due to data hosting bug
starting remote processing and data download
finished downloading data; now writing to file[s]
site nwis_01304200 has all NA values. Skipping file write
site nwis_01408500 has all NA values. Skipping file write
site nwis_01484080 has all NA values. Skipping file write
site nwis_01484085 has all NA values. Skipping file write
site nwis_02110815 has all NA values. Skipping file write
site nwis_02293249 has all NA values. Skipping file write
site nwis_04087120 has all NA values. Skipping file write
site nwis_04087142 has all NA values. Skipping file write
site nwis_04087170 has all NA values. Skipping file write
site nwis_04213152 has all NA values. Skipping file write
site nwis_11046252 has all NA values. Skipping file write
site nwis_11046372 has all NA values. Skipping file write
site nwis_300009090051600 has all NA values. Skipping file write
site nwis_300026090050800 has all NA values. Skipping file write
site nwis_300034090055300 has all NA values. Skipping file write
site nwis_300127090045800 has all NA values. Skipping file write
site nwis_300128090045800 has all NA values. Skipping file write
site nwis_301527088521500 has all NA values. Skipping file write
site nwis_301912088583300 has all NA values. Skipping file write
site nwis_331346117243401 has all NA values. Skipping file write
site nwis_415639070032501 has all NA values. Skipping file write***new***
site nwis_415716070031801 has all NA values. Skipping file write***new***
site nwis_50231500 has all NA values. Skipping file write
site nwis_50231505 has all NA values. Skipping file write
[ BUILD ] sw_gldas                                                |  sw_gldas <- stage_ts("../1_timeseries/out/files_ts_sw_gldas.tsv")
#### STAGING TSES: ATTEMPT 1 ####
staging data for 49 new sites; 702 are already local/posted/unavailable; 751 sites total
omitting these sites for lack of coordinates: 
applying 2 day offset to request due to data hosting bug
starting remote processing and data download
# [still waiting on this one]
```
That looks a lot better. Only the lines above annotated with `***new***` are sites that were new since the last pull but are returning all NA values - i.e., we're adding GLDAS and NLDAS data for the vast majority of those new sites.

**Comment by aappling-usgs** [comment]
Here are the newly added baro and sw sites, for which we should recalculate things:
```r
> (bn <- summarize_ts_files(var_src = 'baro_nldas') %>% filter(upload_date > '2017-01-20') %>% .$site_name %>% sort %>% dput())
c("nwis_01191000", "nwis_01668000", "nwis_0205551460", "nwis_02172002", 
"nwis_03254693", "nwis_03288180", "nwis_03410590", "nwis_03417500", 
"nwis_034324146", "nwis_03432550", "nwis_03433500", "nwis_04085061", 
"nwis_04085082", "nwis_05517500", "nwis_05550001", "nwis_06796500", 
"nwis_06892518", "nwis_08419000", "nwis_12101102", "nwis_410536096194801", 
"nwis_415639070032501", "nwis_415716070031801", "nwis_453250122494501", 
"nwis_453302122491600", "nwis_453312122485800", "nwis_462107111312301"
)
> sn <- summarize_ts_files(var_src = 'sw_nldas') %>% filter(upload_date > '2017-01-20') %>% .$site_name %>% sort
> all.equal(sn, bn)
[1] TRUE

> (bg <- summarize_ts_files(var_src = 'baro_gldas') %>% filter(upload_date > '2017-01-20') %>% .$site_name %>% sort %>% dput())
c("nwis_01191000", "nwis_01668000", "nwis_0205551460", "nwis_02172002", 
"nwis_03254693", "nwis_03288180", "nwis_03410590", "nwis_03417500", 
"nwis_034324146", "nwis_03432550", "nwis_03433500", "nwis_04085061", 
"nwis_04085082", "nwis_05517500", "nwis_05550001", "nwis_06796500", 
"nwis_06892518", "nwis_08419000", "nwis_12101102", "nwis_15236900", 
"nwis_410536096194801", "nwis_453250122494501", "nwis_453302122491600", 
"nwis_453312122485800", "nwis_462107111312301")

> (sg <- summarize_ts_files(var_src = 'sw_nldas') %>% filter(upload_date > '2017-01-20') %>% .$site_name %>% sort %>% dput())
c("nwis_01191000", "nwis_01668000", "nwis_0205551460", "nwis_02172002", 
"nwis_03254693", "nwis_03288180", "nwis_03410590", "nwis_03417500", 
"nwis_034324146", "nwis_03432550", "nwis_03433500", "nwis_04085061", 
"nwis_04085082", "nwis_05517500", "nwis_05550001", "nwis_06796500", 
"nwis_06892518", "nwis_08419000", "nwis_12101102", "nwis_410536096194801", 
"nwis_415639070032501", "nwis_415716070031801", "nwis_453250122494501", 
"nwis_453302122491600", "nwis_453312122485800", "nwis_462107111312301"
)
```

And here are the things we should recalculate:
```r
> tsneeds <- mda.streams::build_calc_ts_needs()
> tsneeds[grep('baro_gldas|baro_nldas', tsneeds$var_src_needs),'var_src']
[1] "dosat_calcGGbts"
> tsneeds[grep('dosat_calcGGbts', tsneeds$var_src_needs),'var_src']
[1] "dopsat_calcObsSat"
> tsneeds[grep('dopsat_calcObsSat', tsneeds$var_src_needs),'var_src']
[1] "doamp_calcDAmp"
> tsneeds[grep('doamp_calcDAmp', tsneeds$var_src_needs),'var_src']
character(0)

> tsneeds[grep('sw_gldas|sw_nldas', tsneeds$var_src_needs),'var_src']
[1] "par_calcSw"
> tsneeds[grep('par_calcSw', tsneeds$var_src_needs),'var_src']
[1] "par_calcLatSw"
> tsneeds[grep('par_calcLatSw', tsneeds$var_src_needs),'var_src']
character(0)
```
The list is therefore:
- [ ] dosat_calcGGbts
- [ ] dopsat_calcObsSat
- [ ] doamp_calcDAmp
- [ ] par_calcSw
- [ ] par_calcLatSw

**Comment by aappling-usgs** [comment]
![image](https://cloud.githubusercontent.com/assets/12039957/22575407/900b53d6-e972-11e6-9667-ee8b1738cc29.png)

|var_src                | total| untouched| no_data| local| posted_untagged| posted_tagged| uncounted| barheight|
|:----------------------|-----:|---------:|-------:|-----:|---------------:|-------------:|---------:|---------:|
|doobs_nwis             |   751|         0|      52|     0|               0|           699|         0|       751|
|wtr_nwis               |   751|         0|      48|     0|               0|           703|         0|       751|
|disch_nwis             |   751|         0|     314|     0|               0|           437|         0|       751|
|baro_nldas             |   751|         0|       6|     0|               0|           745|         0|       751|
|sw_nldas               |   751|         0|       6|     0|               0|           745|         0|       751|
|baro_gldas             |   751|         0|      24|     0|               0|           727|         0|       751|
|sw_gldas               |   751|         0|      24|     0|               0|           727|         0|       751|
|dosat_calcGGbts        |   751|         0|      51|     0|               0|           700|         0|       751|
|baro_calcElev          |   751|         0|     172|     0|               0|           579|         0|       751|
|dosat_calcGGbconst     |   751|         0|     202|     0|               0|           549|         0|       751|
|dopsat_calcObsSat      |   751|         0|      57|     0|               0|           694|         0|       751|
|depth_calcDischRaymond |   751|         0|     314|     0|               0|           437|         0|       751|
|veloc_calcDischRaymond |   751|         0|     314|     0|               0|           437|         0|       751|
|depth_calcDischHarvey  |   751|         0|     364|     0|               0|           387|         0|       751|
|veloc_calcDischHarvey  |   751|         0|     364|     0|               0|           387|         0|       751|
|sitetime_calcLon       |   751|         0|      52|     0|               0|           699|         0|       751|
|suntime_calcLon        |   751|         0|      52|     0|               0|           699|         0|       751|
|par_calcLat            |   751|         0|      52|     0|               0|           699|         0|       751|
|par_calcSw             |   751|         0|       2|     0|               0|           749|         0|       751|
|par_calcLatSw          |   751|         0|      80|     0|               0|           671|         0|       751|
|sitedate_calcLon       |   751|         0|      52|     0|               0|           699|         0|       751|
|doamp_calcDAmp         |   751|         0|      59|     0|               0|           692|         0|       751|
|dischdaily_calcDMean   |   751|         0|     335|     0|               0|           416|         0|       751|
|velocdaily_calcDMean   |   751|         0|     335|     0|               0|           416|         0|       751|
