### ISSUE TITLE
figure: site info

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#186]
multi-panel fig:
National site map, dot size for length of record
distribution of stream discharge or watershed size
histograms of land use classes: urban vs ag vs everything else
Temporal coverage - density plot of record lengths

**Comment by aappling-usgs** [comment]
subsumes #151, #152, #157

**Comment by jread-usgs** [comment]
Cool!

**Comment by aappling-usgs** [comment]
I suppose it's too much for 1/4 of a figure, but here's an interesting way to view the temporal coverage:
![image](https://user-images.githubusercontent.com/12039957/34076112-9679668e-e298-11e7-82a7-eb0abe507db0.png)

and a somewhat more concise way:
![image](https://user-images.githubusercontent.com/12039957/34076162-22cfc550-e29a-11e7-8241-27c42cebc5ff.png)
