### ISSUE TITLE
flesh out spatial metadata

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#218]
tighten up the contents of the spatial metadata files (site_catchment_shapefile.xml at https://www.sciencebase.gov/catalog/item/5a061aa9e4b09af898c74e16 and site_points_shapefile.xml at https://www.sciencebase.gov/catalog/item/5a061bf5e4b09af898c74f2a)

**Comment by aappling-usgs** [comment]
as part of finishing this up, note comments in #216, which changes the list of attributes in the catchments dataset. jordan wrote: "we'll need to propagate that through in catchment_attr.csv, and we might want to consider adding data_source to the points shapefile (all will be NWIS) for completeness, which would then impact points_attr.csv too."
