### ISSUE TITLE
render dates correctly in metadata

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#234]
See https://github.com/USGS-R/meddle/issues/40, where maybe most of this work needs to occur. 

The problem/question is how to include R expressions in meddle YAMLs.
![image](https://user-images.githubusercontent.com/12039957/36991941-8eeecc22-2066-11e8-96cd-63d1dd2cbd9a.png)
https://www.sciencebase.gov/catalog/file/get/59eb9ba6e4b0026a55ffe37f?f=__disk__d9%2Fde%2F0d%2Fd9de0d6f7c9ef8a3e50dd87b53d2f9ddd7d48b6a&transform=1&allowOpen=true

**Comment by aappling-usgs** [comment]
i started to make an edit from
```
end-date: "`r format(as.Date(yaml::yaml.load_file('../1_timeseries/in/ts_config.yml')$times[[2]], '%Y-%m-%d'), '%Y%m%d')"
 ```
to
```
end-date: !expr format(as.Date(yaml::yaml.load_file('../1_timeseries/in/ts_config.yml')$times[[2]], '%Y-%m-%d'), '%Y%m%d')
```
maybe that does it? or not?

**Comment by jread-usgs** [comment]
Note this fail too: https://github.com/USGS-CIDA/stream_metab_usa/pull/233/files#diff-86a49380c9cbc7977e70941a978f0f44

**Comment by jread-usgs** [comment]
maybe this is the warning that I remember? 
```
In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
```

**Comment by jread-usgs** [comment]
@aappling-usgs I pretty much confirmed this is a `yaml` package version issue. I am able to get this to render as expected with
```r
packageVersion('yaml')
[1] ‘2.1.16’
```
but the CRAN version of yaml is 2.1.17, which I think deprecated the auto-evaluation (see above), but I don't see it in the [changelog](https://cran.r-project.org/web/packages/yaml/ChangeLog)

*update* I installed 2.1.17 and it still parsed the date just fine for me. 

I think the 
```
!expr format(as.Date(yaml::yaml.load_file('../1_timeseries/in/ts_config.yml')$times[[2]], '%Y-%m-%d'), '%Y%m%d')
```
solution works, so it is a matter of moving that through and then having aappling build the timeseries and model parts of the release on her machine w/ those changes.

**Comment by jread-usgs** [comment]
This should be done.
