### ISSUE TITLE
Put a nicer title on the spatial data item folder on SB

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#237]
it's the only one with underscore separation now.
```
  Complete fits from metabolism estimation models
  Daily metabolism estimates and predictors
  Input data used for estimating metabolism
  Key diagnostics and overall assessments of metabolism model performance
  Model configurations for estimating metabolism
  Site identifiers and details
  Spatial_data
  Timeseries data collected or computed from outside sources, for estimating or interpreting metabolism
```
https://www.sciencebase.gov/catalog/item/59bff507e4b091459a5e0982

**Comment by aappling-usgs** [comment]
in remake/4_release_spatial.yml, line 86, edit
```
  Spatial_data:
    command: create_release_child(stream_metab_powell_release, target_name)
```
to be
```
  Spatial_data:
    command: create_release_child(stream_metab_powell_release, I('better title goes here'))
```

**Comment by jread-usgs** [comment]
It wasn't as simple as:
```
Spatial_data:
    command: create_release_child(stream_metab_powell_release, I("Spatial data that define site locations and catchments (where available)"))
```

it created an empty item with that title, but didn't put any of the kids into it. Will need to dig deeper on this, or make a smaller helper function `change_sb_title()` in a script as a bandaid.

**Comment by jread-usgs** [comment]
As I hack, I manually edited it using SB's UI. Not sure if it will be overwritten, but let's keep an eye out for it:
![image](https://user-images.githubusercontent.com/2349007/37008046-f1fd11ae-20a5-11e8-8c64-24eedba45f60.png)

**Comment by aappling-usgs** [comment]
Seems like a reasonable approach. We can keep an eye on it.
