### ISSUE TITLE
Transition from private items to SB data release

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#238]
I know we can talk to them, use existing SB items, get a DOI. At what point do we put a nice title (not `stream_metab_powell_release`) on the main item? When/how do we talk to them?

**Comment by aappling-usgs** [comment]
They can provide a reviewer token to give someone access

**Comment by jread-usgs** [comment]
First, Jordan will reach out to Lei Ann and figure out the timeline/process for this.

**Comment by jread-usgs** [comment]
Reached out 2/5/2018

**Comment by aappling-usgs** [comment]
Madison Langseth has set up our current SB item as the final item by adding info to it, so we can ignore my previous comment. She writes, "Once you finalize the data release, let us know and we'll do our final check, we'll make it public, and we'll help you move it wherever you would like."

**Comment by aappling-usgs** [comment]
Using an anonymous access link for submission.
