### ISSUE TITLE
flesh out Process Description steps

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#240]
Determine which of these still need complete descriptions, check off the ones that are done, and add edits (and eventually check marks here) to those that need work.

- [x] AA [Complete fits from metabolism estimation models](https://www.sciencebase.gov/catalog/item/59eb9ba6e4b0026a55ffe37f)
- [x] AA [Daily metabolism estimates and predictors](https://www.sciencebase.gov/catalog/item/59eb9c0ae4b0026a55ffe389)
- [x] JR [Input data used for estimating metabolism](https://www.sciencebase.gov/catalog/item/59eb9b9de4b0026a55ffe37c)
- [x] AA [Key diagnostics and overall assessments of metabolism model performance](https://www.sciencebase.gov/catalog/item/59eb9bafe4b0026a55ffe382)
- [x] JR [Model configurations for estimating metabolism](https://www.sciencebase.gov/catalog/item/59eb9b86e4b0026a55ffe379)
- [x] JR [Site identifiers and details](https://www.sciencebase.gov/catalog/item/59bff64be4b091459a5e098b)
- [x] JR [Spatial catchments](https://www.sciencebase.gov/catalog/item/5a5e37bbe4b06e28e9be48c6)
- [x] JR [Spatial site locations](https://www.sciencebase.gov/catalog/item/5a5e37bde4b06e28e9be48ca)
- [x] AA [Timeseries data collected or computed from outside sources, for estimating or interpreting metabolism](https://www.sciencebase.gov/catalog/item/59c03b72e4b091459a5e0b64)

**Comment by jread-usgs** [comment]
I am adding a small amount of text for the _inputs_ one, which mostly points to the `"High-frequency measurements of metabolism variables" in the accompanying manuscript`

_Site identifiers and details_ is completely empty, and I think I will need some help (probably Ted?) to write this out. It contains a combo of NWIS site metadata, NHDplus info, and coefficients and manual flags, such as`dvqcoefs.m, struct.canal_flag, struct.dam_flag, struct.npdes_flag`

I think _Model configs_ is fine: `Metabolism was estimated using the streamMetabolizer package (Appling et al. 2018) using the Bayesian model with streamMetabolizer model name "b_Kb_oipi_tr_plrckm.stan". This configuration file was generated 2017-04-06 15:04:23 +0000 and was originally labeled with tag 1.0.2.`

_Spatial catchments_ seems fine too: `Existing polygons were combined from various sources (see data_source attribute and Source Information). Spatial tools in the R programming language were used to perform the operations of merging  and modifying attributes.`

_Spatial site locations_ `A points shapefile was created containing locations of the USGS gaging stations included in this data release.  Spatial tools in the R programming language were used to perform the operations of creating the spatial datasets and modifying attributes.` is a little light and I will add to that.

**Comment by jread-usgs** [comment]
My branch for this issue: https://github.com/jread-usgs/stream_metab_usa/tree/descriptions
