### ISSUE TITLE
fill out Native Data Set Environment info

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#242]
This probably varies some from file to file, because each file required different R packages, etc. How unspecific can we get and still feel OK about ourselves?

- [x] AA [Complete fits from metabolism estimation models](https://www.sciencebase.gov/catalog/item/59eb9ba6e4b0026a55ffe37f)
- [x] AA [Daily metabolism estimates and predictors](https://www.sciencebase.gov/catalog/item/59eb9c0ae4b0026a55ffe389)
- [x] JR [Input data used for estimating metabolism](https://www.sciencebase.gov/catalog/item/59eb9b9de4b0026a55ffe37c)
- [x] AA [Key diagnostics and overall assessments of metabolism model performance](https://www.sciencebase.gov/catalog/item/59eb9bafe4b0026a55ffe382)
- [x] JR [Model configurations for estimating metabolism](https://www.sciencebase.gov/catalog/item/59eb9b86e4b0026a55ffe379)
- [x] JR [Site identifiers and details](https://www.sciencebase.gov/catalog/item/59bff64be4b091459a5e098b)
- [x] JR [Spatial catchments](https://www.sciencebase.gov/catalog/item/5a5e37bbe4b06e28e9be48c6)
- [x] JR [Spatial site locations](https://www.sciencebase.gov/catalog/item/5a5e37bde4b06e28e9be48ca)
- [x] AA [Timeseries data collected or computed from outside sources, for estimating or interpreting metabolism](https://www.sciencebase.gov/catalog/item/59c03b72e4b091459a5e0b64)

**Comment by aappling-usgs** [comment]
edit `build-environment:` fields

**Comment by aappling-usgs** [comment]
for spatial files and any others that use `environment_metadata()`, make sure you delete the original data files before running remake to make and push the metadata.

**Comment by aappling-usgs** [comment]
btw, this is an optional field: https://www.fgdc.gov/csdgmgraphical/ideninfo/native.htm

**Comment by jread-usgs** [comment]
good to know

**Comment by jread-usgs** [comment]
I'm wondering which of these this is actually appropriate for. I think the two spatial ones (for sure), but others? Since it is optional, we should only use it where it will end up being useful for users instead of confusing them and making them think they need to replicate the environment for some reason.
