### ISSUE TITLE
Use real URLs to point to data from metadata

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#244]
This involves getting the URLs assigned by ScienceBase

**Comment by aappling-usgs** [comment]
just edit line 11 in metadata_parent.yaml:
```
doi: http://dx.doi.org/10.5066/REPLACE.w.REAL
```

**Comment by aappling-usgs** [comment]
DOI is assigned and jordan edited line 11 and rebuild the 2 spatial metadata files. just need to rebuild the other 7 at some point.

**Comment by jread-usgs** [comment]
Can we switch this one to assigned to you since those rebuilds should probably happen on your comp? Let me know if there are any I should build.

**Comment by aappling-usgs** [comment]
sure, that's fine
