### ISSUE TITLE
install packages from zip files on Condor

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#27]
Shouldn't be too hard to put together a folder of zipped source code so each node doesn't have to download all packages again, right?

**Comment by lawinslow** [comment]
You can definitely do this. [Example of building a file-local repo](https://github.com/USGS-OWI/condor-examples/blob/master/R/run_on_condor.R#L6). I just don't because I've gotten tired of dealing with it.

**Comment by aappling-usgs** [comment]
see `cluster_bundle_packages` in `mda.streams`.
