### ISSUE TITLE
manage condor node crashes

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#29]
luke says you can subset a cluster, e.g., c1[1:5], which means you can drop crashed nodes and then continue to use the cluster.

luke also notes that the node crashes could very well be dplyr, probably in combine_ts when download_ts has failed.

**Comment by aappling-usgs** [comment]
in mda.streams i've now added several retries for download_ts, checks for NULLs in data_list before passing to combine_ts, and checks for NULL within combine_ts. i hope these things will help.

**Comment by aappling-usgs** [comment]
I've put in lots of new error handling in `mda.streams::config_to_data` and `mda.streams::config_to_metab`, so that I'm more confident that the current issue is more about parallel computing than about my `mda.streams code.

With a 1-node cluster, I can run these lines:
```
metab_out <- clusterApplyLB(c1, 1, run_config_to_metab)
metab_out <- clusterApplyLB(c1, 2, run_config_to_metab)
```

but I can't run this - the R process terminates with a pop-up window. It says '_R for Windows front-end has stopped working._ A problem caused the program to stop working correctly. Please close the program.'
```
metab_out <- clusterApplyLB(c1, 1:2, run_config_to_metab)
```

I get the same problem with a 3-node cluster trying to run 2 (or more) run IDs at once.

```
run_config_to_metab <- function(run_id, sleep=runif(1, min=0, max=5)) {
    
  # sleep to avoid sending many similar requests all at once
  Sys.sleep(sleep)
  
  # model metabolism & return results or error
  tryCatch({
    config_to_metab(config, rows=run_id)[[1]]
  }, 
  error=function(e){e})
}
```

**Comment by aappling-usgs** [comment]
Interesting - now I've managed to get a Signal 11 (seg fault) on a serial run of two config rows. I've also received this error about half the time I've tried to run the first row, site nwis_01193050:
```
[1] NA
attr(,"errors")
[1] "Error in FUN(X[[i]], ...): only defined on a data frame with all numeric variables\n"
```

**Comment by lawinslow** [comment]
@aappling-usgs that the real password? May want to drop it.

**Comment by aappling-usgs** [comment]
gah! thanks. yikes. at least it's not my personal password, but still.

**Comment by lawinslow** [comment]
No clue on those errors. You can run it all fine locally though? Can you confirm it's a problem when two or more jobs are running in parallel, or is it seemingly randomly failing? You're running on Windows, right?

**Comment by aappling-usgs** [comment]
I can disconfirm now. See 4 comments up ('serial' = local and without parallel). It's seemingly random.

**Comment by lawinslow** [comment]
Ugh, lame.

**Comment by aappling-usgs** [comment]
Agreed. Thanks for the sympathy =)

**Comment by lawinslow** [comment]
Blame hardware.

**Comment by aappling-usgs** [comment]
I don't want to, but I might need to blame dplyr. I just completely rewrote `streamMetabolizer::mm_model_by_ply` to avoid dplyr, and so far things are working. Knock wood.

**Comment by jread-usgs** [comment]
can you change service account password?

**Comment by aappling-usgs** [comment]
yes, done

**Comment by aappling-usgs** [comment]
running on a local cluster now. will reopen if condor doesn't work, but i'm optimistic.
