### ISSUE TITLE
add non-public DO sites?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#33]
~73 new sites

**Comment by aappling-usgs** [comment]
More sites would be great. Should we make the SB Sites folder non-public if we do this?

**Comment by aappling-usgs** [comment]
notes on public-only data

init_sitelist gives us six sites that end up not having any DO data. those sites might end up being among the non-public DO sites; in the meantime, I'm finding it useful to have a list of those sites and the evidence I have that DO might be available for them:

these sites made it onto the site list but appear to only have daily DO data (suggesting that those min, max, and mean came from an unshared time series of DO data...):
http://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=05406500
http://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=07059998
http://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=07060001

this one has depth-specific DO records for 8 depths - maybe NWIS just can't choose one? also, might be a lake.
http://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=072632995

these maybe have hidden DO data, but there's nothing in the inventory [anymore]. "The data you requested may be available offline. For more information on these data, contact USGS Water Data Support Team":
http://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=071948095
http://waterdata.usgs.gov/nwis/dv?referred_module=sw&site_no=50231505

**Comment by jread-usgs** [comment]
no
