### ISSUE TITLE
No sites in New England ­ are data available elsewhere

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#53]
? Is DO located at a slightly  different site than discharge?

**Comment by jread-usgs** [comment]
sites in New England with `00300`:
-[ ] ME sites: 01036390,01021050
-[ ] NH sites: 01073389,425651070573701,425400070545401,425311070535801
-[ ] VT sites: 
-[ ] MA sites: 01104430,011058798
-[ ] CT sites: 01200600,01201487,01208990,01203000,01208500,01195510,01196528,01196222,01196500,01184000,01193050,01193463,01194750,01124000,01125100
-[ ] RI sites:

**Comment by aappling-usgs** [comment]
Also, USGS 01073389 = Pawtuckaway Lake near Nottingham, NH, so...

overall, this is a lot more sites than we had before, right? I guess these have come online since this summer?

and i assume this is still all just the public ones, right?

**Comment by jread-usgs** [comment]
I am working on the private data too, but it is hard to tell if it is working. Those sites are public above, yes.

**Comment by jread-usgs** [comment]
In our initial data, I think we have one site in Maine and 2 sites in CT

**Comment by jread-usgs** [comment]
this is covered by the gap analysis
