### ISSUE TITLE
Are the ~31 GLRI (Great Lakes Restoration Initiative) stream sites in the database?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#54]

**Comment by jread-usgs** [comment]
list of GLRI sites:
![image](https://cloud.githubusercontent.com/assets/2349007/11045549/b3ab7372-86ed-11e5-84cc-390fd2fc25d6.png)
From Laura: "Looks like the sites lost the leading zeros...no surprise. In R you can use the padZero function in dataRetrieval to put them back in."

**Comment by jread-usgs** [comment]
- [x] nwis_04095090
- [x] nwis_04092750
- [ ] nwis_04032000
- [x] nwis_04040000
- [ ] nwis_04043000
- [ ] nwis_04045500
- [x] nwis_04059500
- [ ] nwis_04059000
- [ ] nwis_04102500
- [x] nwis_04101500
- [ ] nwis_04108670
- [x] nwis_04119400
- [ ] nwis_04122200
- [ ] nwis_04122500
- [x] nwis_04121970
- [ ] nwis_04126000
- [ ] nwis_04056500
- [ ] nwis_04128500
- [ ] nwis_04133501
- [x] nwis_04137500
- [x] nwis_04142000
- [ ] nwis_04157000
- [x] nwis_04166500
- [ ] nwis_04159492
- [x] nwis_04165500
- [x] nwis_04174500
- [x] nwis_04176500
- [ ] nwis_04010500
- [x] nwis_04024000
- [x] nwis_04213500
- [ ] nwis_04218000
- [x] nwis_04231600
- [x] nwis_04249000
- [ ] nwis_04260500
- [ ] nwis_04263000
- [ ] nwis_04265432
- [ ] nwis_04268000
- [ ] nwis_04269000
- [ ] nwis_04193500
- [x] nwis_04195500
- [ ] nwis_04198000
- [x] nwis_04199500
- [ ] nwis_04199000
- [ ] nwis_04201500
- [x] nwis_04200500
- [ ] nwis_04208504
- [ ] nwis_04212100
- [ ] nwis_04024430
- [ ] nwis_04029990
- [ ] nwis_04027500
- [x] nwis_04027000
- [ ] nwis_04071765
- [ ] nwis_04069500
- [x] nwis_04067500
- [ ] nwis_40851385
- [x] nwis_04087170
- [x] nwis_04085427
- [ ] nwis_04126010
- [ ] nwis_04132052
- [ ] nwis_04135000
- [ ] nwis_04133501
- [ ] nwis_04135020
- [x] nwis_04157005
- [ ] nwis_04086600
- [ ] nwis_04087000
- [x] nwis_04193490
- [x] nwis_04208000
- [ ] nwis_0410832081262100
- [ ] nwis_04200000
- [ ] nwis_04160900
- [ ] nwis_04106000
- [ ] nwis_04086000
- [ ] nwis_04087000

**Comment by jread-usgs** [comment]
update here @aappling-usgs. the checked sites we have in powstreams. The unchecked boxes we do not. The high-frequency data that exist for the sites we *don't* have are in parens. The sites that are unchecked and have nothing behind them only have discrete data. For those following at home, we have 27 of these sites in powstreams. I was under the impression 31 of the sites had YSI EXOs, but that could have been a slight exaggeration.

**Comment by jread-usgs** [comment]
so looks like we aren't missing any of these sites that have `00300`.

**Comment by aappling-usgs** [comment]
27 is still pretty darn good. glad to hear we have them all.

**Comment by jread-usgs** [comment]
I am going to close this out.
