### ISSUE TITLE
update all data to binary

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#68]
would love for this to leave previous data versions archived on SB within the same items - a technical issue for mda.streams, but putting b/c i'd like us to wait on reposting data until we have the technical means of archiving in place.

**Comment by jread-usgs** [comment]
am working on this now. 

An issue that showed up with our hosting of NLDAS data ( #73 ) is that the data from NASA and the data from CIDA are offset by 2 days...which is really odd. I need to fix that (whatever the cause) before doing all of the `stage_nldas_ts` runs:

![image](https://cloud.githubusercontent.com/assets/2349007/14292395/823f3cce-fb2d-11e5-8f2f-e44283bd7d0a.png)

black is CIDA hosted data, red is a smaller chunk of NASA hosted data for the same param, and green is the NASA data+two full days offset.

**Comment by appling** [comment]
wow, excellent that you caught this now rather than later!

**Comment by aappling-usgs** [comment]
wow, excellent that you caught this now rather than later!

**Comment by jread-usgs** [comment]
@jiwalker-usgs per our convo, the opendap subset returns the same time offset

**Comment by jread-usgs** [comment]
Nevermind, using OPeNDAP subset actually moves the *NASA* data, but not the CIDA hosted data:

No offsets applied, both are opendap:
![image](https://cloud.githubusercontent.com/assets/2349007/14294610/967954a4-fb37-11e5-844b-248b4b1fb101.png)

blue is the data coming back from the feature weighted process

**Comment by jread-usgs** [comment]
so, now my question is: which offset is actually right?

**Comment by jread-usgs** [comment]
Well, tracking down data from an observatory tells us that this offset is very likely false (also did an altitude adjustment on the obs data because they are on top of a very tall building):

![image](https://cloud.githubusercontent.com/assets/2349007/14295777/a3416d3e-fb3c-11e5-8552-3f55a781f9fd.png)

red color is CIDA hosted data w/ the +2day offset applied.

**Comment by jread-usgs** [comment]
Testing this agains't NASA services:

```r
fabric
An object of class "webdata":
times: 2016-03-26T00:00:00Z, 2016-03-31T00:00:00Z
url: dods://hydro1.sci.gsfc.nasa.gov/dods/NLDAS_FORA0125_H.002 
variables: pressfc

job1 = geoknife(c(-89.40897, 43.07061), fabric)
job2 = geoknife(c(-89.40897, 43.07061), fabric, 'subset', OUTPUT_TYPE='netcdf')

# waiting

feature.data <- result(job1)
nc.data <- nc_open(download(job2))

plot(feature.data$DateTime, feature.data$bufferedPoint, xlim=c(as.POSIXct(c("2016-03-26 UTC", "2016-04-02 UTC"))))
points(as.POSIXct('01-01-01', tz='UTC')+ncdf4::ncvar_get(nc.data, 'time')*86400, ncdf4::ncvar_get(nc.data, 'pressfc')[2,2,], col='red')
```
![image](https://cloud.githubusercontent.com/assets/2349007/14296342/45132718-fb3f-11e5-899d-74919a600eaa.png)

**Comment by jread-usgs** [comment]
So, in summary, writing the intermediate netcdf file, which happened with our use of `nccopy` and also with `OPeNDAP Subset` on the GDP, a two day offset is added in the netcdf writing stage. This doesn't seem to be a GDP bug, it is either a bug in netcdf, or in NASA's implementation, or some other thing?

**Comment by dblodgett-usgs** [comment]
It would be helpful to see the services in question here. I suspect there is an issue with calendar attributes.

**Comment by jread-usgs** [comment]
Yes, 

That first timestamp comes back as expected from that call: 
```r
as.POSIXct('01-01-01', tz='UTC')+722451.5833333334*86400
[1] "1979-01-03 14:00:00 UTC"
```
Which is the beginning of the dataset (`grads_min: "13z01jan1979" `)

Thanks for taking a look @dblodgett-usgs . Not sure what the best path is - re-write the time attribute and re-host, or deal with the gotcha in the post-processing.

**Comment by jread-usgs** [comment]
for post-processing:

*add* 172800 to the initial time request (shift the time forward)
*subtract* 172800 from the results

**Comment by dblodgett-usgs** [comment]
We should look at the ncdump output from what the GDP's OPeNDAP subset creates as well as what nccopy creates. There's a lot of nuance that's not necessarily apparent with this kind of calendar. I suspect there's an issue with attributes and/or conventions some place.

**Comment by jread-usgs** [comment]
Confirmed the post-processing approach above returns the same data as hitting NASA's services directly. 
NASA is red, grey is CIDA-hosted with the +172800 on the request and the -172800 on the result:
![image](https://cloud.githubusercontent.com/assets/2349007/14318290/bc5d762e-fbd1-11e5-9895-7571d0ee3b93.png)

**Comment by jread-usgs** [comment]
@dblodgett-usgs per ncml convos:

```r
library(geoknife)
library(ncdf4)
gconfig(wps.url="http://cida-test.er.usgs.gov/gdp/process/WebProcessingService", wait=TRUE)

url.coards = 'http://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/nldas_temp3.ncml'
url.grads = 'http://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/nldas_temp2.ncml'



job.coards.fwgs = geoknife(c(-89.40897, 43.07061), webdata(url=url.coards, variable = 'pressfc', times=c('2015-06-01','2015-06-08')))
plot(result(job.coards.fwgs)[c('DateTime','bufferedPoint')])
job.coards.nc = geoknife(c(-89.40897, 43.07061), webdata(url=url.coards, variable = 'pressfc', times=c('2015-06-01','2015-06-08')),'subset', OUTPUT_TYPE='netcdf')
nc <- nc_open(download(job.coards.nc))
points(as.POSIXct('01-01-01', tz='UTC')+ncdf4::ncvar_get(nc, 'time')*86400, ncdf4::ncvar_get(nc, 'pressfc')[2,2,], col='red', pch=3)
graphics::title('COARDS convention')

job.grads.fwgs = geoknife(c(-89.40897, 43.07061), webdata(url=url.grads, variable = 'pressfc', times=c('2015-06-01','2015-06-08')))
plot(result(job.grads.fwgs)[c('DateTime','bufferedPoint')])
job.grads.nc = geoknife(c(-89.40897, 43.07061), webdata(url=url.grads, variable = 'pressfc', times=c('2015-06-01','2015-06-08')),'subset', OUTPUT_TYPE='netcdf')
nc <- nc_open(download(job.grads.nc))
points(as.POSIXct('01-01-01', tz='UTC')+ncdf4::ncvar_get(nc, 'time')*86400, ncdf4::ncvar_get(nc, 'pressfc')[2,2,], col='red', pch=3)
graphics::title('GrADs convention')
```
![image](https://cloud.githubusercontent.com/assets/2349007/14320808/10140ddc-fbdc-11e5-9e1e-111ba96a1706.png)

![image](https://cloud.githubusercontent.com/assets/2349007/14320814/18250490-fbdc-11e5-8df3-be8ebc6c9168.png)

**Comment by jread-usgs** [comment]
w/o any convention:
![image](https://cloud.githubusercontent.com/assets/2349007/14322448/99576a3e-fbe2-11e5-9013-e579a1b489a0.png)

@dblodgett-usgs

**Comment by jread-usgs** [comment]
dataset after replacing `.ncml` w/ conventions removed:

`$ head nldas.ncml`
```xml
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" xmlns:xlink="http://www.w3.org/1999/xlink">
  <aggregation type="union">
    <remove type="attribute" name="Conventions"/>
    <netcdf>
      <aggregation type="joinExisting" dimName="time">
        <netcdf location="NLDAS_236675.237674_0.223_0.463_pressfc.nc"/>
        <netcdf location="NLDAS_237675.238674_0.223_0.463_pressfc.nc"/>
        <netcdf location="NLDAS_238675.239674_0.223_0.463_pressfc.nc"/>
        <netcdf location="NLDAS_239675.240674_0.223_0.463_pressfc.nc"/>
        <netcdf location="NLDAS_240675.241674_0.223_0.463_pressfc.nc"/>
```

```r
url = 'http://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/nldas.ncml'
job.nldas = geoknife(c(-89.40897, 43.07061), webdata('nldas', variable = 'pressfc', times=c('2015-06-01 00:00','2015-06-01 04:00')))
job.cida = geoknife(c(-89.40897, 43.07061), webdata(url=url, variable = 'pressfc', times=c('2015-05-28 00:00','2015-06-05 04:00')))
plot(result(job.coards.fwgs)[c('DateTime','bufferedPoint')], col='red', pch=3)
points(result(job.coards.nldas)[c('DateTime','bufferedPoint')])
```

![image](https://cloud.githubusercontent.com/assets/2349007/14581356/92f3b8fc-03b0-11e6-8f72-a1b62815d8e3.png)

W/o conventions, we get consistent behavior between FWGS and subset, but we still have an offset from the original dataset (at least now that offset is consistent?). @dblodgett-usgs seems we can't just modify the .ncml to get it to agree w/ the original host's data?

**Comment by jread-usgs** [comment]
```r
url = 'http://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/nldas.ncml'
job.fwgs = geoknife(c(-89.40897, 43.07061), webdata(url=url, variable = 'pressfc', times=c('2015-06-01','2015-06-08')))
plot(result(job.fwgs)[c('DateTime','bufferedPoint')])
job.nc = geoknife(c(-89.40897, 43.07061), webdata(url=url, variable = 'pressfc', times=c('2015-06-01','2015-06-08')),'subset', OUTPUT_TYPE='netcdf')
nc <- nc_open(download(job.nc))
points(as.POSIXct('01-01-01', tz='UTC')+ncdf4::ncvar_get(nc, 'time')*86400, ncdf4::ncvar_get(nc, 'pressfc')[2,2,], col='red', pch=3)
graphics::title('No convention')
```
![image](https://cloud.githubusercontent.com/assets/2349007/14581392/9e82dfe4-03b1-11e6-9478-120b491cc432.png)

**Comment by dblodgett-usgs** [comment]
The time index can't be 'fixed' because it's not broken. FWGS given GrADS or no conventions converts the time index 'correctly' and all other methods are converting using some normal method that results in 'incorrect' output dates.

The problem, if we want to call it a problem, lies in the as.POSIXct('01-01-01', tz='UTC') and assuming that we can just add the time stamps to that origin to get modern dates. Whatever R does in that case, is what FWGS does when it uses COARDS conventions. The 'correct' thing is whatever NetCDF-Java/FWGS does when it uses its 'default' calendar -- which is what gets used given GrADS conventions.

It would be interesting to use chron to do the NetCDF date conversion and see if it handles this the same as FWGS. There's an example of how to do that here: https://github.com/dblodgett-usgs/climates/blob/master/R/CF_date_range.R#L65

So, the 'fix' here is to find out how to appropriately convert dates represented with a year 1 origin, not 'fix' the data so a normal conversion works 'correctly'.

**Comment by jread-usgs** [comment]
To be clear @dblodgett-usgs I don't think this is an R POSIX issue. I am using FWGS on a cida hosted slice of .nc data that I used nccopy to subset from NASA. It comes out of FWGS off by two days, w/o touching R. 

So re-writing the dime dimension seems to be the preferred solution?

**Comment by dblodgett-usgs** [comment]
I'm so confused. Lets follow up in person.

**Comment by jread-usgs** [comment]
in the future, we should write a single nc file that is just time, as ints (hours since ...) and add this to the ncml

**Comment by jread-usgs** [comment]
For completeness as to where we are w/ NASA vs CIDA hosted NLDAS, here is the FWGS comparison @dblodgett-usgs (this just confirms our discussion, but removes the copy paste error I had above in the code):

```r
url = 'http://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/nldas.ncml'
job.nldas = geoknife(c(-89.40897, 43.07061), webdata('nldas', variable = 'pressfc', times=c('2015-06-01 00:00','2015-06-05 04:00')), wait=T)
job.cida = geoknife(c(-89.40897, 43.07061), webdata(url=url, variable = 'pressfc', times=c('2015-05-28 00:00','2015-06-05 04:00')), wait=T)
plot(result(job.cida)[c('DateTime','bufferedPoint')], col='red', pch=3)
points(result(job.nldas)[c('DateTime','bufferedPoint')])
```
![image](https://cloud.githubusercontent.com/assets/2349007/14605816/fd671928-053f-11e6-954d-cdaf1fe8f04b.png)

**Comment by dblodgett-usgs** [comment]
After a chat with @rsignell-usgs I think that overwriting the time index using our knowledge of the actual minimum date of the source data and the known offset from that minimum date to the subset of the dataset we have at EROS is the most reasonable path forward. This discussion is a good summary of the ambiguity of the 1-1-1 date origin. https://www.myroms.org/forum/viewtopic.php?f=14&t=69&hilit=mjd

**Comment by jread-usgs** [comment]
done?
