### ISSUE TITLE
Update make for sites and nwis/nldas

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#76]
Related to #68 , but I wanted to capture to-do items and that issue is more about the data itself

- [x] need a comprehensive "initialize sites" that creates a file that lists sites that are superset of all sites in the project now, plus sites that meet criteria. This should be an improvement from the first time around because we know some more things about specifying site rules (e.g, let's ignore `'ES'` (estuary) sites). 
- [x] need to have the nldas and nwis make both use this site file
- [x] capture those steps in the yaml, create functions as needed.

**Comment by jread-usgs** [comment]
- [ ] fix hosting of NLDAS so the data bump hack is not required

**Comment by jread-usgs** [comment]
hmm...`get_site_coords` is going to skip over any of the new sites because they aren't in the metadata. will need to get lat/lon for `geoknife` elsewhere, **or**, is making/updating the table a step that should precede getting data for the sites?

**Comment by aappling-usgs** [comment]
making/updating the coordinates table happens in `stage_meta_basic()` - i think that can be called as soon as all sites are posted (can just be empty items).

**Comment by jread-usgs** [comment]
Finding trouble with initialize and understanding what files already exist (since we don't do retries on data fails). I suggest we move to this more complicated structure as a tsv instead of just a vector of site names:


| file                              | local | remote | time.st      | time.en      | no.data |
|-----------------------------------|-------|--------|--------------|--------------|--------------|
| "nwis_11463682-ts_doobs_nwis.rds" | FALSE | FALSE  | "2006-10-01" | "2016-03-01" | FALSE |
| "nwis_12098700-ts_doobs_nwis.rds" | FALSE | FALSE  | "2006-10-01" | "2016-03-01" |  FALSE |

**Comment by jread-usgs** [comment]
Progress on this - working well, but one pain point is that stage_nwis_ts returns the same thing regardless of whether it hit an error w NWIS or if there is legitimately no data (both return a data.frame(), which then results in no file). There is a message, but we can't capture and act on a message. 

This is important for the `no.data` column. I added a warning() to my fork of `mda.streams` when we run into a dataRet error, which I catch and treat accordingly. This is kind of a bandaid for the issue, but I wanted to note it here.

**Comment by aappling-usgs** [comment]
Your warning in your mda.streams fork seems like a good idea. interested in making it an official part of mda.streams? and/or want me to work more directly on getting `stage_nwis_ts` to be informative about reasons for empty data? I could prioritize that task next if it would be useful.

**Comment by jread-usgs** [comment]
Update on progress - this works pretty well, but I would like to avoid blowing away the table when it already exists (unless maybe a `clean` is used?). This way if something is remote, it doesn't get reset to FALSE and we have to look it up again.

Also, would like to check remote (not just local and no.data) before building the jobs in nwis and nldas. This will make it possible to ship around the tables in version control, and have it still work properly on a different computer.

**Comment by aappling-usgs** [comment]
Checking remote before building jobs seems like a good idea. Also applies to calculated tses. For all types of tses, the fastest way to check remotes is to `list_sites(var_src)` and check whether your `site_name` is in the list or not. (as opposed to, e.g., querying each site for its own tses, or trying to locate tses with locate_ts)

**Comment by jread-usgs** [comment]
@aappling-usgs can this be closed?
