### ISSUE TITLE
make/remake for nwis

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-CIDA/stream_metab_usa#88]
probably includes getting rid of old makefile, which i think is very out of date

this issue is the lingering task from #76

**Comment by jread-usgs** [comment]
I think a lot of this (all of this?) is in `1_timeseries.yml`

**Comment by aappling-usgs** [comment]
pretty much. still need to get rid of old makefile, etc. but yes, nwis ts files get remade correctly already.
