### ISSUE TITLE
add file staging functions to make workflow

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/stream_metab_usa#9]
https://github.com/USGS-CIDA/stream_metab_usa/blob/master/makefile#L22

need to update the `stage_nwis_ts` and `stage_nldas_ts` functions for sites. @aappling-usgs can you share your desired pattern for nwis and I can populate for nldas?

**Comment by aappling-usgs** [comment]
yes, see #10 (especially p1_import/code folder)

**Comment by jread-usgs** [comment]
gotcha, thanks
